# Generated by Django 2.1.1 on 2018-12-14 21:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20181213_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updaterequest',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='updaterequest',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
