# Generated by Django 2.1.1 on 2018-12-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20181214_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterathometimelog',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entertimelog',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outathometimelog',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outtimelog',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
