# Generated by Django 2.1.1 on 2018-12-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20181215_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterathometimelog',
            name='text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entertimelog',
            name='text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='outathometimelog',
            name='text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='outtimelog',
            name='half_day_off',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='outtimelog',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
