# Generated by Django 2.1.1 on 2018-12-16 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20181216_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updaterequest',
            options={},
        ),
        migrations.RemoveField(
            model_name='updaterequest',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='updaterequest',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='updaterequest',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='updaterequest',
            name='status',
        ),
    ]
