# Generated by Django 2.1.1 on 2018-12-16 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_updaterequest_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterathometimelog',
            name='token',
        ),
        migrations.RemoveField(
            model_name='entertimelog',
            name='token',
        ),
        migrations.RemoveField(
            model_name='outathometimelog',
            name='token',
        ),
        migrations.RemoveField(
            model_name='outtimelog',
            name='token',
        ),
    ]
