# Generated by Django 2.1.1 on 2018-12-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20181216_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='updaterequest',
            name='status',
            field=models.IntegerField(choices=[(0, '대기중'), (1, '수락'), (2, '거절')], default=0),
        ),
    ]
