# Generated by Django 2.1.1 on 2018-12-16 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_updaterequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterUpdateRequest',
            fields=[
                ('updaterequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.UpdateRequest')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='originRequestInfo', to='user.EnterTimelog')),
            ],
            bases=('user.updaterequest',),
        ),
        migrations.CreateModel(
            name='OutUpdateRequest',
            fields=[
                ('updaterequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.UpdateRequest')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='originRequestInfo', to='user.OutTimelog')),
            ],
            bases=('user.updaterequest',),
        ),
        migrations.RemoveField(
            model_name='updaterequest',
            name='origin',
        ),
    ]
