# Generated by Django 2.1.1 on 2018-12-16 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_auto_20181217_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterupdaterequest',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='originEnterRequestInfo', to='user.EnterTimelog'),
        ),
        migrations.AlterField(
            model_name='outupdaterequest',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='originOutRequestInfo', to='user.OutTimelog'),
        ),
    ]
