# Generated by Django 2.1.1 on 2018-12-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_usertime'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertimelog',
            name='keyword',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
