# Generated by Django 2.1.1 on 2018-12-16 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_auto_20181217_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterupdaterequest',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='enterupdaterequest',
            name='updaterequest_ptr',
        ),
        migrations.RemoveField(
            model_name='outupdaterequest',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='outupdaterequest',
            name='updaterequest_ptr',
        ),
        migrations.AddField(
            model_name='updaterequest',
            name='origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='originRequestInfo', to='user.EnterTimelog'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EnterUpdateRequest',
        ),
        migrations.DeleteModel(
            name='OutUpdateRequest',
        ),
    ]
