# Generated by Django 2.1.1 on 2018-12-17 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_auto_20181217_0932'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTime',
        ),
    ]
